---
name: dist
"on":
  push:
    branches: [master, explo/gh-actions]
jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.19.1"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libgtk-3-dev libcairo2-dev libglib2.0-dev

      - name: Run `make dist`
        run: make dist

      - name: Upload dist package
        uses: actions/upload-artifact@v3
        with:
          name: dist-package
          path: target/Gomics*.zip
